---
title: "Displaying Tables with GT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gt)
library(palmerpenguins)
```


```{r}
penguins %>% 
  group_by(species) %>%
  summarise_at(
    .vars = c(
      "bill_length_mm",
      "flipper_length_mm",
      "body_mass_g"),
    .funs = ~ mean(., na.rm = TRUE)
  ) %>%
  gt(rowname_col = "species") %>%
  tab_header(
    title = "Penguins Data Set",
    subtitle = "Data collected from three penguin species from three islands"
  ) %>%
  opt_align_table_header(align = "left") %>%
  cols_label(
    bill_length_mm = md("Bill Length,<br>mm"),
    flipper_length_mm = md("Flipper Length,<br>mm"),
    body_mass_g = md("Body Mass,<br>kg")
  ) %>%
  fmt_number(columns = everything()) %>%
  fmt_number(columns = body_mass_g, scale_by = 1/1000) %>%
  cols_width(
    bill_length_mm ~ px(150),
    flipper_length_mm ~ px(150),
    body_mass_g ~ px(150)
  ) %>%
  tab_source_note(
    source_note = md("Data from the `palmerpenguins` **R** Package")
  ) %>%
  tab_footnote(
    footnote = "The largest of the three penguin species",
    locations = cells_stub(rows = "Gentoo")
  ) %>%
  tab_style(
    locations = cells_body(
      columns = everything(),
      rows = "Gentoo"
    ),
    style = list(
      cell_fill(color = "darkblue"),
      cell_text(color = "white")
      )
  ) %>% 
  tab_stubhead(
    label = md("Penguin *species*")
  ) %>%
  opt_table_font(
    font = google_font("Monsterrat")
  )
```

